version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      # Монтируем корень проекта (опционально) или только базу и статику
      # Важно: монтируем файл БД так, чтобы рядом могли создаваться -wal файлы
      - ./game.db:/app/game.db
      - ./static/images:/app/static/images
      # Если планируешь делать бэкапы через скрипт в main.py
      - ./backups:/app/backups
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
    networks:
      - bot_net

networks:
  bot_net:
    driver: bridge
