version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: always
    ports:
      - "3000:3000"  # Совпадаем с Dockerfile и ожиданиями Bothost
    env_file: .env
    volumes:
      - ./game.db:/app/game.db
      # Пробрасываем картинки внутрь папки static, чтобы они были доступны WebApp
      - ./images:/app/static/images 
    networks:
      - bot_net

  redis:
    image: redis:7-alpine
    container_name: bot_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bot_net

networks:
  bot_net:

volumes:
  redis_data:
