version: '3.8'

services:
  bot:
    build: .
    container_name: tg_bot
    restart: always
    ports:
      - "8080:8080"  # Внешний порт 8080 : Внутренний порт 8080
    env_file: .env
    volumes:
      - ./game.db:/app/game.db
      - ./images:/app/images
    networks:
      - bot_net

  redis:
    image: redis:7-alpine
    container_name: bot_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bot_net

networks:
  bot_net:

volumes:
  redis_data:
